import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyNavBar from "@/components/ui/MyNavBar";
import { Toaster } from "sonner";
import { RouteChangeTracker } from "@/components/route-change-tracker";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Jonathans Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50`}
      >
        <Suspense fallback={null}> 
          <RouteChangeTracker/>
        </Suspense>
        
        <MyNavBar/>
        {children}
        <Toaster position="top-center"/>
      </body>
    </html>
  );
}